SERVICE_TOKEN={{ SERVICE_TOKEN }}
ADMIN_PASSWORD={{ ADMIN_PASSWORD }}
SERVICE_PASSWORD={{ SERVICE_PASSWORD }}

RABBIT_HOST={{ RABBIT_HOST }}
RABBIT_USER={{ RABBIT_USER }}
RABBIT_PASSWORD={{ RABBIT_PASSWORD }}

DATABASE_TYPE=mysql
DATABASE_PASSWORD={{ DATABASE_PASSWORD }}
DATABASE_HOST={{ DATABASE_HOST }}
DATABASE_USER={{ DATABASE_USER }}

MYSQL_DRIVER=PyMySQL
MYSQL_HOST={{ DATABASE_HOST }}
MYSQL_USER={{ DATABASE_USER }}
MYSQL_PASSWORD={{ DATABASE_PASSWORD }}

LOGFILE=/opt/stack/logs/stack.sh.log
VERBOSE=True
LOG_COLOR=False
SCREEN_LOGDIR=/opt/stack/logs
ENABLE_DEBUG_LOG_LEVEL=true

GIT_BASE=${GIT_BASE:-https://git.openstack.org}
