# State identifiers (begin and end).

NO_STATE = -1

BIND_START = 0
BIND_END = BIND_START + 1

INTER_SSH_START = 10
INTER_SSH_END = INTER_SSH_START + 1

GIT_SETUP_START = 20
GIT_SETUP_END = GIT_SETUP_START + 1

UPLOAD_REPO_START = 30
UPLOAD_REPO_END = UPLOAD_REPO_START + 1

INSTALL_PKG_START = 40
INSTALL_PKG_END = INSTALL_PKG_START + 1

CLONE_STACK_START = 50
CLONE_STACK_END = CLONE_STACK_START + 1

PATCH_STACK_START = 60
PATCH_STACK_END = PATCH_STACK_START + 1

UPLOAD_EXTRAS_START = 70
UPLOAD_EXTRAS_END = UPLOAD_EXTRAS_START + 1

CREATE_LOCAL_START = 80
CREATE_LOCAL_END = CREATE_LOCAL_START + 1

STACK_SH_START = 100
STACK_SH_END = STACK_START + 1
