#!/usr/bin/env ansible-playbook
---

# Creates a new instance in godaddy internal cloud.
- name: Launch needed VM instances.
  hosts: localhost
  tasks:
  - name: Launch needed 'map' VM instance.
    os_server:
      state: present
      name: "{{ user }}-map-1"
      wait: true
      # This will likely need to change for the user...
      key_name: "{{ key_name }}"
      # This may need to be updated as newer versions arrive...
      image: centos7-base-20160809a-0.0.7-1.el7
      flavor: m1.medium
      # This isn't super-great and may require further adjustment if/once
      # this az fills up (but for now its fine).
      availability_zone: "phx-private-cor-zone-2"
